Pull upstream: Fix various Yielder leaks. #9934
Summary:
Pull upstream: Fix various Yielder leaks. #9934: https://github.com/apache/druid/pull/9934

Background:
"select" query in 0.14 is deprecated in 0.16 and gets replaced by scan query. There's a bug in scan query that doesn't close yielder properly and the resource leakage overtime will reach the limit and become unrecoverable and throw exceptions for all subsequent scan queries. The time to failure from a fresh cluster restart shortens as QPS gets higher. This upstream change fixed the issue including multiple other related issues.

Initial stacktrace:
2020-08-07 01:07:24,422 [finagle/netty3-2] (ArchmageDruidBackend.java:246) ERROR Request {"query":"SELECT TIME_FORMAT(__time, 'YYYY-MM-dd') AS dt FROM conversion_quality_health_scores WHERE (__time >= TIMESTAMP '2020-07-31 00:00:00.000000' AND __time <= TIMESTAMP '2020-08-07 00:00:00.000000') ORDER BY __time DESC LIMIT 1"} failed with Druid response code 500 and response body {"error":"Unknown exception","errorMessage":"Attempt to register more than 65535 parties for org.apache.druid.segment.ReferenceCountingSegment$1@4448b3db[phase = 0 parties = 65535 arrived = 0]","errorClass":"java.lang.IllegalStateException","host":"druid-storage-shared-data-hot-0a01e878.ec2.pin220.com:9090"}

Test Plan: Verified the resource gets freed properly after adding logs in ReferenceCountingSegment increment and decrement.

Reviewers: O1139 Druid, jgu

Reviewed By: O1139 Druid, jgu

Subscribers: jenkins, mleonard, #realtime-analytics

JIRA Issue(s): RTA-1675

Differential Revision: https://phabricator.pinadmin.com/D606912